### ISSUE TITLE
get prices from bonbast

### ISSUE THREAD

**Issue by msabaeian** [hmralavi/NerkhBackend#1]
let's get prices from https://bonbast.com/ cause they show prices of free market, you can use this package for it:
https://github.com/SamadiPour/bonbast

**Comment by hmralavi** [comment]
Done. we now get the bonbast prices from its python package (the one you mentioned).
we use `bonbast.main.get_prices()` for getting the live prices.
there is another way to get the prices from the terminal:
https://github.com/SamadiPour/rial-exchange-rates-archive/blob/main/get_next.py

we can use the second solution in the future if needed. but for now, our current solution works well.
