### ISSUE TITLE
car prices

### ISSUE THREAD

**Issue by msabaeian** [hmralavi/NerkhBackend#2]
we need to find a reliable source to get car prices, persianapi provide one but I'm not sure how reliable it is (https://persianapi.com/product/%d8%a8%d8%a7%d8%b2%d8%a7%d8%b1-%d8%ae%d9%88%d8%af%d8%b1%d9%88/)

also karname has a lot pages with car prices: https://karnameh.com/car-price

**Comment by hmralavi** [comment]
car prices are available at https://www.iranjib.ir/.
we've been using it for several years.
it should be easy to extract the prices by a crawler.

**Comment by hmralavi** [comment]
I did the codes to obtain prices for 6 cars from this source:
https://www.iranjib.ir/showgroup/45/%D9%82%DB%8C%D9%85%D8%AA-%D8%AE%D9%88%D8%AF%D8%B1%D9%88-%D8%AA%D9%88%D9%84%DB%8C%D8%AF-%D8%AF%D8%A7%D8%AE%D9%84/

the prices are availbale in our api at:
https://nerkh-api-dev.liara.run/

NOTE: i made a minor modification in the json data structure. see:
https://nerkh-api-dev.liara.run/docs#/default/get_prices_get_prices_post

@msabaeian please check the json data structure and see if it's ok. then i can proceed with the prices for more cars.

**Comment by msabaeian** [comment]
Nice implementation! a few comments from me, none of them are blocking at this stage:
- price1 and price2 can have better names, maybe max_price and min_price, or higher_price and lower_price. in any case, 1 and 2 suffixes don't make sense to me
- can you add gzip compression to the response? while the data is not too much I expect it will be a lot more soon, so it's good to compress the response from now.
- it is a bit strange/odd to send raw data without a key in restful APIs, it's better to have codes as a valid key to filter response data: ‍`curl -d {codes: ['USD'] }`

**Comment by hmralavi** [comment]
- sure, i agree with higher_price and lower_price. will modify it.
- ok sure
- so as far as i understood, instead of this:

      [
        {
          "code": "USD-TMN",
          "category": "currency",
          "description": "US Dollar - IR Toman",
          "source": "bonbast",
          "price1": 64500,
          "price2": 64400,
          "price1_change": 0,
          "price2_change": 0,
          "time": "2024-04-21T23:00:15.028982+03:30"
        },
        {
          "code": "EUR-TMN",
          "category": "currency",
          "description": "EURO - IR Toman",
          "source": "bonbast",
          "price1": 68800,
          "price2": 68700,
          "price1_change": 0,
          "price2_change": 0,
          "time": "2024-04-21T23:00:15.029243+03:30"
        }
      ]
  
you want this:
  
       {
          "USD-TMN": {
              "code": "USD-TMN",
              "category": "currency",
              "description": "US Dollar - IR Toman",
              "source": "bonbast",
              "price1": 64500,
              "price2": 64400,
              "price1_change": 0,
              "price2_change": 0,
              "time": "2024-04-21T23:00:15.028982+03:30"
          },
          "EUR-TMN": {
              "code": "EUR-TMN",
              "category": "currency",
              "description": "EURO - IR Toman",
              "source": "bonbast",
              "price1": 68800,
              "price2": 68700,
              "price1_change": 0,
              "price2_change": 0,
              "time": "2024-04-21T23:00:15.029243+03:30"
          }
       }

right?

**Comment by msabaeian** [comment]
@hmralavi No I meant for request payload

so instead of:
`curl -X 'POST' 'https://nerkh-api-dev.liara.run/get_prices' -H 'accept: application/json' -H 'Content-Type: application/json' -d '["USD-TMN", "EUR-TMN"]'`

this:
`curl -X 'POST' 'https://nerkh-api-dev.liara.run/get_prices' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"codes":["USD-TMN", "EUR-TMN"]}'`

sorry I didn't convey my point in the last message correctly
